language: c++
sudo: required
dist: trusty

addons: &addons
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - libfaad-dev
      - libfaad2
      - automake
      - g++-6

script:
  - |
    ./bootstrap.sh
    CC=gcc-6 CXX=g++-6 ./configure
    make
  - |
    wget http://downloads.sourceforge.net/faac/faad2-2.7.tar.bz2
    tar -f faad2-2.7.tar.bz2 -x
    cd faad2-2.7
    CC=gcc-6 CXX=g++-6 ./configure
    make
    cd ..
    make CC=gcc-6 CXX=g++-6 -f Makefile.faadalyse

