language: c++
os: linux
dist: focal

addons: &addons
  apt:
    packages: &packages
      - libzmq3-dev
      - libzmq5
      - libfaad-dev
      - libfaad2
      - automake
      - g++-10

script:
  - |
    export CC=gcc-10
    export CXX=g++-10
    ./bootstrap.sh
    ./configure
    make
  - |
    export CC=gcc-10
    export CXX=g++-10
    wget http://downloads.sourceforge.net/faac/faad2-2.7.tar.bz2
    tar -f faad2-2.7.tar.bz2 -x
    cd faad2-2.7
    ./configure
    make
    cd ..
    make -f Makefile.faadalyse

