language: c++
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons: &addons
  apt:
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - libboost1.55-all-dev
      - libfaad-dev
      - libfaad2
      - automake

script:
  - |
    ./bootstrap.sh
    CC=clang CXX=clang++ ./configure
    make
  - |
    ./bootstrap.sh
    ./configure
    make

